root = "."
tmp_dir = "docker/air/tmp"

[build]
  bin = "docker/air/tmp/main"
  cmd = "go build -o docker/air/tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]

[log]
  level = "debug"
